feat: Replace root Dockerfile with mathcomp/{dual,single}/Dockerfile
* Add ARG commands
* Simplify RUN commands by using a shell form.

diff --git a/mathcomp/dual/Dockerfile b/mathcomp/dual/Dockerfile
--- a/mathcomp/dual/Dockerfile
+++ b/mathcomp/dual/Dockerfile
@@ -1,23 +1,15 @@
-FROM coqorg/coq:dev
+ARG COQ_TAG="dev"
+FROM coqorg/coq:${COQ_TAG}
 
-ENV MATHCOMP_VERSION="dev"
+ARG MATHCOMP_VERSION="dev"
+ENV MATHCOMP_VERSION=${MATHCOMP_VERSION}
 ENV MATHCOMP_PACKAGE="coq-mathcomp-character"
 
-RUN ["/bin/bash", "--login", "-c", "set -x \
-  && eval $(opam env --switch=${COMPILER_EDGE} --set-switch) \
-  && opam update -y -u \
-  && opam pin add -n -k version coq-mathcomp-ssreflect ${MATHCOMP_VERSION} \
-  && opam pin add -n -k version coq-mathcomp-fingroup ${MATHCOMP_VERSION} \
-  && opam pin add -n -k version coq-mathcomp-algebra ${MATHCOMP_VERSION} \
-  && opam pin add -n -k version coq-mathcomp-solvable ${MATHCOMP_VERSION} \
-  && opam pin add -n -k version coq-mathcomp-field ${MATHCOMP_VERSION} \
-  && opam pin add -n -k version coq-mathcomp-character ${MATHCOMP_VERSION} \
-  && opam install -y -j ${NJOBS} ${MATHCOMP_PACKAGE} \
-  && opam clean -a -c -s --logs \
-  && opam config list && opam list"]
+SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]
 
-RUN ["/bin/bash", "--login", "-c", "set -x \
-  && eval $(opam env --switch=${COMPILER} --set-switch) \
+# hadolint ignore=SC2046
+RUN set -x \
+  && eval $(opam env "--switch=${COMPILER_EDGE}" --set-switch) \
   && opam update -y -u \
   && opam pin add -n -k version coq-mathcomp-ssreflect ${MATHCOMP_VERSION} \
   && opam pin add -n -k version coq-mathcomp-fingroup ${MATHCOMP_VERSION} \
@@ -27,4 +19,22 @@ RUN ["/bin/bash", "--login", "-c", "set -x \
   && opam pin add -n -k version coq-mathcomp-character ${MATHCOMP_VERSION} \
   && opam install -y -j ${NJOBS} ${MATHCOMP_PACKAGE} \
   && opam clean -a -c -s --logs \
-  && opam config list && opam list"]
+  && opam config list && opam list
+
+# hadolint ignore=SC2046
+RUN set -x \
+  && eval $(opam env "--switch=${COMPILER}" --set-switch) \
+  && opam update -y -u \
+  && opam pin add -n -k version coq-mathcomp-ssreflect ${MATHCOMP_VERSION} \
+  && opam pin add -n -k version coq-mathcomp-fingroup ${MATHCOMP_VERSION} \
+  && opam pin add -n -k version coq-mathcomp-algebra ${MATHCOMP_VERSION} \
+  && opam pin add -n -k version coq-mathcomp-solvable ${MATHCOMP_VERSION} \
+  && opam pin add -n -k version coq-mathcomp-field ${MATHCOMP_VERSION} \
+  && opam pin add -n -k version coq-mathcomp-character ${MATHCOMP_VERSION} \
+  && opam install -y -j ${NJOBS} ${MATHCOMP_PACKAGE} \
+  && opam clean -a -c -s --logs \
+  && opam config list && opam list
+
+# Restore default shell to fully preserve backward compatibility
+SHELL ["/bin/sh", "-c"]
+# Still, we may remove this line later on.
